// <auto-generated />
using System;
using BiebWebApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BiebWebApp.Migrations
{
    [DbContext(typeof(BiebWebAppContext))]
    [Migration("20230610125235_YourMigrationName")]
    partial class YourMigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BiebWebApp.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemType")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Abigayle Moore",
                            ItemType = 3,
                            Location = "Kilbackfort",
                            Status = 0,
                            Title = "Small Cotton Fish",
                            Year = 2016
                        },
                        new
                        {
                            Id = 2,
                            Author = "Clay Toy",
                            ItemType = 2,
                            Location = "Port Aaliyahshire",
                            Status = 0,
                            Title = "Generic Cotton Soap",
                            Year = 2011
                        },
                        new
                        {
                            Id = 3,
                            Author = "Aglae Effertz",
                            ItemType = 2,
                            Location = "East Jayda",
                            Status = 0,
                            Title = "Ergonomic Rubber Bacon",
                            Year = 2011
                        },
                        new
                        {
                            Id = 4,
                            Author = "Margot Johns",
                            ItemType = 0,
                            Location = "Keelingburgh",
                            Status = 0,
                            Title = "Intelligent Wooden Shoes",
                            Year = 2006
                        },
                        new
                        {
                            Id = 5,
                            Author = "Alba Rowe",
                            ItemType = 3,
                            Location = "Harryfort",
                            Status = 0,
                            Title = "Handmade Concrete Chair",
                            Year = 2011
                        },
                        new
                        {
                            Id = 6,
                            Author = "Talon Hackett",
                            ItemType = 1,
                            Location = "West Katarina",
                            Status = 0,
                            Title = "Unbranded Fresh Ball",
                            Year = 2017
                        },
                        new
                        {
                            Id = 7,
                            Author = "Quinten Stracke",
                            ItemType = 0,
                            Location = "Ashtonmouth",
                            Status = 0,
                            Title = "Small Granite Hat",
                            Year = 2006
                        },
                        new
                        {
                            Id = 8,
                            Author = "Pearl Corwin",
                            ItemType = 3,
                            Location = "Evalynport",
                            Status = 0,
                            Title = "Unbranded Plastic Car",
                            Year = 2010
                        },
                        new
                        {
                            Id = 9,
                            Author = "Eldred Heller",
                            ItemType = 1,
                            Location = "Nicolachester",
                            Status = 0,
                            Title = "Licensed Plastic Mouse",
                            Year = 2023
                        },
                        new
                        {
                            Id = 10,
                            Author = "Dariana Lind",
                            ItemType = 3,
                            Location = "East Enid",
                            Status = 0,
                            Title = "Unbranded Rubber Bike",
                            Year = 2015
                        },
                        new
                        {
                            Id = 11,
                            Author = "Dorian Jacobi",
                            ItemType = 3,
                            Location = "Boehmbury",
                            Status = 0,
                            Title = "Tasty Frozen Pants",
                            Year = 2008
                        },
                        new
                        {
                            Id = 12,
                            Author = "Birdie Flatley",
                            ItemType = 1,
                            Location = "New June",
                            Status = 0,
                            Title = "Incredible Rubber Bacon",
                            Year = 2016
                        },
                        new
                        {
                            Id = 13,
                            Author = "Christiana Hegmann",
                            ItemType = 3,
                            Location = "New Diamondborough",
                            Status = 0,
                            Title = "Handmade Frozen Chicken",
                            Year = 2010
                        },
                        new
                        {
                            Id = 14,
                            Author = "Irma Becker",
                            ItemType = 2,
                            Location = "Hoegermouth",
                            Status = 0,
                            Title = "Ergonomic Rubber Pants",
                            Year = 2007
                        },
                        new
                        {
                            Id = 15,
                            Author = "Jalen Stanton",
                            ItemType = 2,
                            Location = "New Mckenziefort",
                            Status = 0,
                            Title = "Refined Steel Chips",
                            Year = 2020
                        },
                        new
                        {
                            Id = 16,
                            Author = "Llewellyn Dickinson",
                            ItemType = 2,
                            Location = "Gleasonville",
                            Status = 0,
                            Title = "Generic Granite Table",
                            Year = 2013
                        },
                        new
                        {
                            Id = 17,
                            Author = "Doris Dare",
                            ItemType = 0,
                            Location = "Abrahamfort",
                            Status = 0,
                            Title = "Tasty Granite Shirt",
                            Year = 2015
                        },
                        new
                        {
                            Id = 18,
                            Author = "Emmitt Stiedemann",
                            ItemType = 3,
                            Location = "North Maci",
                            Status = 0,
                            Title = "Licensed Rubber Chicken",
                            Year = 2006
                        },
                        new
                        {
                            Id = 19,
                            Author = "Sharon Oberbrunner",
                            ItemType = 2,
                            Location = "Port Haylie",
                            Status = 0,
                            Title = "Incredible Rubber Fish",
                            Year = 2023
                        },
                        new
                        {
                            Id = 20,
                            Author = "Dakota Mante",
                            ItemType = 0,
                            Location = "South Marisolside",
                            Status = 0,
                            Title = "Awesome Fresh Bacon",
                            Year = 2018
                        },
                        new
                        {
                            Id = 21,
                            Author = "Anita Reichel",
                            ItemType = 2,
                            Location = "Port Lucytown",
                            Status = 0,
                            Title = "Gorgeous Cotton Bike",
                            Year = 2022
                        },
                        new
                        {
                            Id = 22,
                            Author = "Garnett Torp",
                            ItemType = 1,
                            Location = "Nathanaelburgh",
                            Status = 0,
                            Title = "Rustic Plastic Pants",
                            Year = 2017
                        },
                        new
                        {
                            Id = 23,
                            Author = "Lessie Beier",
                            ItemType = 0,
                            Location = "North Abbey",
                            Status = 0,
                            Title = "Gorgeous Fresh Fish",
                            Year = 2013
                        },
                        new
                        {
                            Id = 24,
                            Author = "Paul Windler",
                            ItemType = 1,
                            Location = "Ziemefurt",
                            Status = 0,
                            Title = "Small Granite Car",
                            Year = 2015
                        },
                        new
                        {
                            Id = 25,
                            Author = "Tina O'Reilly",
                            ItemType = 2,
                            Location = "New Katelinchester",
                            Status = 0,
                            Title = "Sleek Wooden Chips",
                            Year = 2020
                        },
                        new
                        {
                            Id = 26,
                            Author = "Harold Moore",
                            ItemType = 0,
                            Location = "West Deven",
                            Status = 0,
                            Title = "Sleek Wooden Tuna",
                            Year = 2000
                        },
                        new
                        {
                            Id = 27,
                            Author = "Beau Douglas",
                            ItemType = 1,
                            Location = "Jacintotown",
                            Status = 0,
                            Title = "Awesome Steel Pizza",
                            Year = 2023
                        },
                        new
                        {
                            Id = 28,
                            Author = "Hillary Satterfield",
                            ItemType = 3,
                            Location = "Ovashire",
                            Status = 0,
                            Title = "Handcrafted Plastic Hat",
                            Year = 2012
                        },
                        new
                        {
                            Id = 29,
                            Author = "Teresa Hoppe",
                            ItemType = 0,
                            Location = "East Adriel",
                            Status = 0,
                            Title = "Unbranded Granite Ball",
                            Year = 2006
                        },
                        new
                        {
                            Id = 30,
                            Author = "Humberto Kertzmann",
                            ItemType = 2,
                            Location = "Parisianton",
                            Status = 0,
                            Title = "Awesome Steel Tuna",
                            Year = 2014
                        },
                        new
                        {
                            Id = 31,
                            Author = "Gaston Harris",
                            ItemType = 1,
                            Location = "Bethelton",
                            Status = 0,
                            Title = "Handmade Rubber Bacon",
                            Year = 2011
                        },
                        new
                        {
                            Id = 32,
                            Author = "Conner Hagenes",
                            ItemType = 1,
                            Location = "Yundtfort",
                            Status = 0,
                            Title = "Handmade Plastic Salad",
                            Year = 2015
                        },
                        new
                        {
                            Id = 33,
                            Author = "Flossie Carter",
                            ItemType = 0,
                            Location = "Sethfort",
                            Status = 0,
                            Title = "Refined Rubber Soap",
                            Year = 2007
                        },
                        new
                        {
                            Id = 34,
                            Author = "Cathy Bashirian",
                            ItemType = 1,
                            Location = "Kennedishire",
                            Status = 0,
                            Title = "Intelligent Metal Bacon",
                            Year = 2001
                        },
                        new
                        {
                            Id = 35,
                            Author = "Glennie Schumm",
                            ItemType = 2,
                            Location = "Bergeville",
                            Status = 0,
                            Title = "Fantastic Metal Pants",
                            Year = 2019
                        },
                        new
                        {
                            Id = 36,
                            Author = "Wilton Spinka",
                            ItemType = 0,
                            Location = "New Cordelia",
                            Status = 0,
                            Title = "Practical Metal Shirt",
                            Year = 2019
                        },
                        new
                        {
                            Id = 37,
                            Author = "Lily Erdman",
                            ItemType = 0,
                            Location = "Port Lydia",
                            Status = 0,
                            Title = "Sleek Fresh Keyboard",
                            Year = 2012
                        },
                        new
                        {
                            Id = 38,
                            Author = "Maybell Wolf",
                            ItemType = 2,
                            Location = "Prosaccoborough",
                            Status = 0,
                            Title = "Intelligent Wooden Car",
                            Year = 2005
                        },
                        new
                        {
                            Id = 39,
                            Author = "Gonzalo Cronin",
                            ItemType = 2,
                            Location = "Dedricburgh",
                            Status = 0,
                            Title = "Incredible Steel Soap",
                            Year = 2023
                        },
                        new
                        {
                            Id = 40,
                            Author = "Rosie Breitenberg",
                            ItemType = 3,
                            Location = "Shyannview",
                            Status = 0,
                            Title = "Tasty Soft Chicken",
                            Year = 2020
                        },
                        new
                        {
                            Id = 41,
                            Author = "Alice Kirlin",
                            ItemType = 3,
                            Location = "Gleichnerville",
                            Status = 0,
                            Title = "Rustic Granite Chicken",
                            Year = 2002
                        },
                        new
                        {
                            Id = 42,
                            Author = "Shyann Monahan",
                            ItemType = 2,
                            Location = "New Berthafurt",
                            Status = 0,
                            Title = "Unbranded Concrete Salad",
                            Year = 2007
                        },
                        new
                        {
                            Id = 43,
                            Author = "Jayden Leffler",
                            ItemType = 0,
                            Location = "Lake Garth",
                            Status = 0,
                            Title = "Intelligent Plastic Shirt",
                            Year = 2014
                        },
                        new
                        {
                            Id = 44,
                            Author = "Karen Cormier",
                            ItemType = 0,
                            Location = "New Greysonstad",
                            Status = 0,
                            Title = "Awesome Wooden Cheese",
                            Year = 2014
                        },
                        new
                        {
                            Id = 45,
                            Author = "Mason Hayes",
                            ItemType = 0,
                            Location = "East Jakayla",
                            Status = 0,
                            Title = "Handcrafted Cotton Ball",
                            Year = 2000
                        },
                        new
                        {
                            Id = 46,
                            Author = "Barbara VonRueden",
                            ItemType = 1,
                            Location = "Macview",
                            Status = 0,
                            Title = "Unbranded Concrete Ball",
                            Year = 2006
                        },
                        new
                        {
                            Id = 47,
                            Author = "Maci Kertzmann",
                            ItemType = 2,
                            Location = "New Ewaldmouth",
                            Status = 0,
                            Title = "Generic Soft Soap",
                            Year = 2012
                        },
                        new
                        {
                            Id = 48,
                            Author = "Nia Romaguera",
                            ItemType = 3,
                            Location = "East Reinhold",
                            Status = 0,
                            Title = "Licensed Rubber Mouse",
                            Year = 2002
                        },
                        new
                        {
                            Id = 49,
                            Author = "Elisha Rolfson",
                            ItemType = 0,
                            Location = "West Daron",
                            Status = 0,
                            Title = "Unbranded Concrete Car",
                            Year = 2002
                        },
                        new
                        {
                            Id = 50,
                            Author = "Taurean Konopelski",
                            ItemType = 2,
                            Location = "Kiehnview",
                            Status = 0,
                            Title = "Gorgeous Soft Salad",
                            Year = 2016
                        },
                        new
                        {
                            Id = 51,
                            Author = "Amely Hills",
                            ItemType = 1,
                            Location = "North Kennith",
                            Status = 0,
                            Title = "Incredible Soft Fish",
                            Year = 2011
                        },
                        new
                        {
                            Id = 52,
                            Author = "Akeem Wolf",
                            ItemType = 0,
                            Location = "Kobyshire",
                            Status = 0,
                            Title = "Ergonomic Cotton Cheese",
                            Year = 2015
                        },
                        new
                        {
                            Id = 53,
                            Author = "Akeem Collier",
                            ItemType = 0,
                            Location = "East Jermainstad",
                            Status = 0,
                            Title = "Unbranded Concrete Gloves",
                            Year = 2017
                        },
                        new
                        {
                            Id = 54,
                            Author = "Mabel Keebler",
                            ItemType = 2,
                            Location = "Jakubowskitown",
                            Status = 0,
                            Title = "Generic Soft Towels",
                            Year = 2021
                        },
                        new
                        {
                            Id = 55,
                            Author = "Andre Homenick",
                            ItemType = 2,
                            Location = "Wisozktown",
                            Status = 0,
                            Title = "Fantastic Concrete Keyboard",
                            Year = 2017
                        },
                        new
                        {
                            Id = 56,
                            Author = "Adolfo Welch",
                            ItemType = 0,
                            Location = "Jenningsmouth",
                            Status = 0,
                            Title = "Handmade Steel Sausages",
                            Year = 2022
                        },
                        new
                        {
                            Id = 57,
                            Author = "Aditya Orn",
                            ItemType = 3,
                            Location = "Alecstad",
                            Status = 0,
                            Title = "Generic Fresh Salad",
                            Year = 2007
                        },
                        new
                        {
                            Id = 58,
                            Author = "Reid Hansen",
                            ItemType = 3,
                            Location = "Douglastown",
                            Status = 0,
                            Title = "Refined Cotton Table",
                            Year = 2008
                        },
                        new
                        {
                            Id = 59,
                            Author = "Rhianna Gislason",
                            ItemType = 3,
                            Location = "East Lura",
                            Status = 0,
                            Title = "Fantastic Soft Car",
                            Year = 2002
                        },
                        new
                        {
                            Id = 60,
                            Author = "Brad Gislason",
                            ItemType = 3,
                            Location = "Predovicburgh",
                            Status = 0,
                            Title = "Awesome Frozen Towels",
                            Year = 2017
                        },
                        new
                        {
                            Id = 61,
                            Author = "Wiley Stark",
                            ItemType = 2,
                            Location = "Malachistad",
                            Status = 0,
                            Title = "Unbranded Steel Hat",
                            Year = 2022
                        },
                        new
                        {
                            Id = 62,
                            Author = "Richard Larson",
                            ItemType = 1,
                            Location = "East Gregoryview",
                            Status = 0,
                            Title = "Awesome Cotton Table",
                            Year = 2023
                        },
                        new
                        {
                            Id = 63,
                            Author = "Eleanore Mitchell",
                            ItemType = 0,
                            Location = "North Gabe",
                            Status = 0,
                            Title = "Small Wooden Fish",
                            Year = 2008
                        },
                        new
                        {
                            Id = 64,
                            Author = "Anna Torphy",
                            ItemType = 0,
                            Location = "Ziemeland",
                            Status = 0,
                            Title = "Intelligent Frozen Computer",
                            Year = 2002
                        },
                        new
                        {
                            Id = 65,
                            Author = "Damien Bahringer",
                            ItemType = 1,
                            Location = "Runolfssonborough",
                            Status = 0,
                            Title = "Small Fresh Sausages",
                            Year = 2000
                        },
                        new
                        {
                            Id = 66,
                            Author = "Rebeka Roberts",
                            ItemType = 3,
                            Location = "West Mauricioberg",
                            Status = 0,
                            Title = "Fantastic Cotton Fish",
                            Year = 2005
                        },
                        new
                        {
                            Id = 67,
                            Author = "Corine Fisher",
                            ItemType = 1,
                            Location = "West Victoria",
                            Status = 0,
                            Title = "Licensed Plastic Computer",
                            Year = 2022
                        },
                        new
                        {
                            Id = 68,
                            Author = "Raphaelle Schimmel",
                            ItemType = 2,
                            Location = "Holliehaven",
                            Status = 0,
                            Title = "Handcrafted Concrete Computer",
                            Year = 2004
                        },
                        new
                        {
                            Id = 69,
                            Author = "Rebeca Tremblay",
                            ItemType = 2,
                            Location = "Deloresside",
                            Status = 0,
                            Title = "Sleek Rubber Hat",
                            Year = 2013
                        },
                        new
                        {
                            Id = 70,
                            Author = "Barney Walter",
                            ItemType = 2,
                            Location = "West Aurelio",
                            Status = 0,
                            Title = "Fantastic Frozen Sausages",
                            Year = 2000
                        },
                        new
                        {
                            Id = 71,
                            Author = "Mose Breitenberg",
                            ItemType = 3,
                            Location = "Port Sage",
                            Status = 0,
                            Title = "Tasty Plastic Soap",
                            Year = 2012
                        },
                        new
                        {
                            Id = 72,
                            Author = "Gabe Haag",
                            ItemType = 2,
                            Location = "Karistad",
                            Status = 0,
                            Title = "Intelligent Steel Ball",
                            Year = 2021
                        },
                        new
                        {
                            Id = 73,
                            Author = "Burley Ziemann",
                            ItemType = 0,
                            Location = "East Granville",
                            Status = 0,
                            Title = "Ergonomic Plastic Towels",
                            Year = 2009
                        },
                        new
                        {
                            Id = 74,
                            Author = "Buck Larkin",
                            ItemType = 1,
                            Location = "Gradyfort",
                            Status = 0,
                            Title = "Refined Metal Pizza",
                            Year = 2015
                        },
                        new
                        {
                            Id = 75,
                            Author = "Unique Schimmel",
                            ItemType = 0,
                            Location = "Anabelchester",
                            Status = 0,
                            Title = "Incredible Plastic Ball",
                            Year = 2013
                        },
                        new
                        {
                            Id = 76,
                            Author = "Ladarius Aufderhar",
                            ItemType = 3,
                            Location = "North Jordibury",
                            Status = 0,
                            Title = "Incredible Cotton Shirt",
                            Year = 2011
                        },
                        new
                        {
                            Id = 77,
                            Author = "Lonie Considine",
                            ItemType = 3,
                            Location = "Daughertyton",
                            Status = 0,
                            Title = "Generic Rubber Pizza",
                            Year = 2004
                        },
                        new
                        {
                            Id = 78,
                            Author = "Kassandra Ortiz",
                            ItemType = 0,
                            Location = "Leonardville",
                            Status = 0,
                            Title = "Fantastic Cotton Bike",
                            Year = 2008
                        },
                        new
                        {
                            Id = 79,
                            Author = "Keagan Bednar",
                            ItemType = 0,
                            Location = "Shanonbury",
                            Status = 0,
                            Title = "Unbranded Concrete Mouse",
                            Year = 2000
                        },
                        new
                        {
                            Id = 80,
                            Author = "Lorenza Prosacco",
                            ItemType = 2,
                            Location = "Lake Carolyne",
                            Status = 0,
                            Title = "Handcrafted Cotton Chair",
                            Year = 2013
                        },
                        new
                        {
                            Id = 81,
                            Author = "Ellsworth Bruen",
                            ItemType = 1,
                            Location = "Edwinaton",
                            Status = 0,
                            Title = "Sleek Metal Chips",
                            Year = 2022
                        },
                        new
                        {
                            Id = 82,
                            Author = "Cleo Langosh",
                            ItemType = 3,
                            Location = "Port Trevionburgh",
                            Status = 0,
                            Title = "Licensed Fresh Cheese",
                            Year = 2014
                        },
                        new
                        {
                            Id = 83,
                            Author = "Dustin Leffler",
                            ItemType = 0,
                            Location = "Cedrickmouth",
                            Status = 0,
                            Title = "Gorgeous Fresh Hat",
                            Year = 2018
                        },
                        new
                        {
                            Id = 84,
                            Author = "Eryn Herman",
                            ItemType = 1,
                            Location = "West Julie",
                            Status = 0,
                            Title = "Handmade Cotton Soap",
                            Year = 2011
                        },
                        new
                        {
                            Id = 85,
                            Author = "Newton Jerde",
                            ItemType = 2,
                            Location = "West Israel",
                            Status = 0,
                            Title = "Small Soft Pizza",
                            Year = 2002
                        },
                        new
                        {
                            Id = 86,
                            Author = "Darrick McClure",
                            ItemType = 0,
                            Location = "New Gloria",
                            Status = 0,
                            Title = "Gorgeous Granite Pants",
                            Year = 2023
                        },
                        new
                        {
                            Id = 87,
                            Author = "Doyle Dach",
                            ItemType = 3,
                            Location = "West Gaylord",
                            Status = 0,
                            Title = "Practical Rubber Pants",
                            Year = 2005
                        },
                        new
                        {
                            Id = 88,
                            Author = "Elenor Pfannerstill",
                            ItemType = 0,
                            Location = "Sydneyside",
                            Status = 0,
                            Title = "Intelligent Frozen Towels",
                            Year = 2006
                        },
                        new
                        {
                            Id = 89,
                            Author = "Makenzie Maggio",
                            ItemType = 1,
                            Location = "Homenickfort",
                            Status = 0,
                            Title = "Gorgeous Steel Sausages",
                            Year = 2017
                        },
                        new
                        {
                            Id = 90,
                            Author = "Davon Monahan",
                            ItemType = 1,
                            Location = "North Lessie",
                            Status = 0,
                            Title = "Awesome Granite Shirt",
                            Year = 2009
                        },
                        new
                        {
                            Id = 91,
                            Author = "Kailey Jaskolski",
                            ItemType = 2,
                            Location = "New Brookfort",
                            Status = 0,
                            Title = "Intelligent Plastic Soap",
                            Year = 2005
                        },
                        new
                        {
                            Id = 92,
                            Author = "Dameon Wisozk",
                            ItemType = 0,
                            Location = "East Vito",
                            Status = 0,
                            Title = "Ergonomic Cotton Soap",
                            Year = 2014
                        },
                        new
                        {
                            Id = 93,
                            Author = "Gloria Kerluke",
                            ItemType = 3,
                            Location = "Schroederport",
                            Status = 0,
                            Title = "Fantastic Plastic Table",
                            Year = 2020
                        },
                        new
                        {
                            Id = 94,
                            Author = "Bailey Mann",
                            ItemType = 1,
                            Location = "New Duncanstad",
                            Status = 0,
                            Title = "Tasty Concrete Computer",
                            Year = 2003
                        },
                        new
                        {
                            Id = 95,
                            Author = "Cleta Bins",
                            ItemType = 1,
                            Location = "Wehnerfort",
                            Status = 0,
                            Title = "Small Rubber Bacon",
                            Year = 2010
                        },
                        new
                        {
                            Id = 96,
                            Author = "Elisa Lind",
                            ItemType = 0,
                            Location = "Araceliview",
                            Status = 0,
                            Title = "Gorgeous Wooden Car",
                            Year = 2017
                        },
                        new
                        {
                            Id = 97,
                            Author = "Annabel Moore",
                            ItemType = 0,
                            Location = "Macejkovicchester",
                            Status = 0,
                            Title = "Handcrafted Steel Chair",
                            Year = 2017
                        },
                        new
                        {
                            Id = 98,
                            Author = "Jade Pfannerstill",
                            ItemType = 3,
                            Location = "Muellershire",
                            Status = 0,
                            Title = "Practical Rubber Chips",
                            Year = 2014
                        },
                        new
                        {
                            Id = 99,
                            Author = "Earline Buckridge",
                            ItemType = 1,
                            Location = "Goldaberg",
                            Status = 0,
                            Title = "Gorgeous Plastic Towels",
                            Year = 2022
                        },
                        new
                        {
                            Id = 100,
                            Author = "Trey Swift",
                            ItemType = 2,
                            Location = "South Evan",
                            Status = 0,
                            Title = "Sleek Soft Towels",
                            Year = 2005
                        });
                });

            modelBuilder.Entity("BiebWebApp.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoanDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 90,
                            LoanDate = new DateTime(2022, 8, 14, 4, 56, 35, 467, DateTimeKind.Local).AddTicks(8336),
                            ReservationId = 3,
                            ReturnDate = new DateTime(2024, 2, 7, 15, 11, 19, 461, DateTimeKind.Local).AddTicks(5621),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 75,
                            LoanDate = new DateTime(2022, 11, 22, 10, 16, 29, 148, DateTimeKind.Local).AddTicks(5492),
                            ReservationId = 1,
                            ReturnDate = new DateTime(2023, 9, 13, 19, 19, 53, 870, DateTimeKind.Local).AddTicks(4378),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 57,
                            LoanDate = new DateTime(2022, 7, 13, 23, 54, 36, 649, DateTimeKind.Local).AddTicks(7332),
                            ReservationId = 3,
                            ReturnDate = new DateTime(2023, 6, 13, 9, 15, 5, 982, DateTimeKind.Local).AddTicks(7668),
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 20,
                            LoanDate = new DateTime(2022, 8, 31, 0, 46, 3, 7, DateTimeKind.Local).AddTicks(7831),
                            ReservationId = 5,
                            ReturnDate = new DateTime(2023, 7, 9, 2, 19, 30, 450, DateTimeKind.Local).AddTicks(9159),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 5,
                            LoanDate = new DateTime(2023, 2, 11, 18, 16, 41, 154, DateTimeKind.Local).AddTicks(1975),
                            ReservationId = 2,
                            ReturnDate = new DateTime(2023, 12, 23, 6, 55, 55, 54, DateTimeKind.Local).AddTicks(9289),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("BiebWebApp.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LocationName = "East Samanthaberg"
                        },
                        new
                        {
                            Id = 2,
                            LocationName = "Stehrport"
                        },
                        new
                        {
                            Id = 3,
                            LocationName = "Wiltonport"
                        },
                        new
                        {
                            Id = 4,
                            LocationName = "West Kendra"
                        },
                        new
                        {
                            Id = 5,
                            LocationName = "Nikostad"
                        },
                        new
                        {
                            Id = 6,
                            LocationName = "Freemanhaven"
                        },
                        new
                        {
                            Id = 7,
                            LocationName = "West Charles"
                        },
                        new
                        {
                            Id = 8,
                            LocationName = "North Murphy"
                        },
                        new
                        {
                            Id = 9,
                            LocationName = "Parisborough"
                        },
                        new
                        {
                            Id = 10,
                            LocationName = "Aronfort"
                        });
                });

            modelBuilder.Entity("BiebWebApp.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 79,
                            ReservationDate = new DateTime(2022, 7, 16, 6, 20, 19, 46, DateTimeKind.Local).AddTicks(5182),
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 95,
                            ReservationDate = new DateTime(2022, 7, 11, 4, 57, 31, 224, DateTimeKind.Local).AddTicks(8223),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 92,
                            ReservationDate = new DateTime(2022, 10, 3, 13, 28, 54, 594, DateTimeKind.Local).AddTicks(9831),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ItemId = 11,
                            ReservationDate = new DateTime(2023, 3, 29, 23, 34, 4, 688, DateTimeKind.Local).AddTicks(3174),
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            ItemId = 94,
                            ReservationDate = new DateTime(2023, 4, 27, 9, 16, 59, 765, DateTimeKind.Local).AddTicks(7929),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BiebWebApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPaid")
                        .HasColumnType("bit");

                    b.Property<bool>("HasSubscription")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MaxItemsPerYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "486ff1fa-3e33-44ea-8155-e555170fdf61",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            HasPaid = false,
                            HasSubscription = false,
                            IsBlocked = false,
                            LockoutEnabled = true,
                            MaxItemsPerYear = 0,
                            Name = "Administrator",
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMLA2nLaDCgtBrPktB+lQtEwzrPpBg579Ow2P/Mxcb5wR6Gz78/FhJ2OpuX4H3jxlg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d35b2475-d904-4282-abba-5f242db7edcb",
                            SubscriptionType = "4",
                            TwoFactorEnabled = false,
                            Type = 2,
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "107dfe4c-8dc7-4826-a54e-3627e9aece80",
                            Email = "librarian@example.com",
                            EmailConfirmed = true,
                            HasPaid = false,
                            HasSubscription = false,
                            IsBlocked = false,
                            LockoutEnabled = true,
                            MaxItemsPerYear = 0,
                            Name = "Librarian",
                            NormalizedEmail = "LIBRARIAN@EXAMPLE.COM",
                            NormalizedUserName = "LIBRARIAN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEI1mJDY7R1mDmT1VSXqpdAy1KopLrzoRNROF1fcmRdXATaZM36CGoh0BsrCqf8fI2g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "236ae7d5-b3ef-427e-8591-38c829a8357d",
                            SubscriptionType = "3",
                            TwoFactorEnabled = false,
                            Type = 1,
                            UserName = "librarian@example.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "83106efa-84ee-4076-9e1d-f03228c9e622",
                            Email = "member@example.com",
                            EmailConfirmed = true,
                            HasPaid = false,
                            HasSubscription = false,
                            IsBlocked = false,
                            LockoutEnabled = true,
                            MaxItemsPerYear = 0,
                            Name = "Member",
                            NormalizedEmail = "MEMBER@EXAMPLE.COM",
                            NormalizedUserName = "MEMBER@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEF0MxRCmpPFhKn1IYvHTsvwMgFYq5K/2fmLNYwH9rEPqxoUkcQiJgb/5XJlkyjewBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7cf5296a-feb7-4bee-a8e6-6d07ac514825",
                            SubscriptionType = "2",
                            TwoFactorEnabled = false,
                            Type = 0,
                            UserName = "member@example.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0fcf5948-7d36-4eb1-aedd-fe384d035817",
                            Email = "Breanna89@gmail.com",
                            EmailConfirmed = true,
                            HasPaid = false,
                            HasSubscription = false,
                            IsBlocked = false,
                            LockoutEnabled = true,
                            MaxItemsPerYear = 0,
                            Name = "Maci Hauck",
                            NormalizedEmail = "NICK_DAUGHERTY@HOTMAIL.COM",
                            NormalizedUserName = "MYLES.GLOVER@YAHOO.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAENkHGYfw7CrzCY+cUJvNk3VKBtHjskbaWK0mHNwrNI46A+37A9JYQdNnqXakRrm36g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e9bfa93e-15e2-461c-824e-ac20e401d16a",
                            SubscriptionType = "1",
                            TwoFactorEnabled = false,
                            Type = 0,
                            UserName = "Alexanne16@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "85db415b-5132-40ce-a4e7-1fddfdad12ee",
                            Email = "Polly.Bernhard@gmail.com",
                            EmailConfirmed = true,
                            HasPaid = false,
                            HasSubscription = false,
                            IsBlocked = false,
                            LockoutEnabled = true,
                            MaxItemsPerYear = 0,
                            Name = "Penelope Medhurst",
                            NormalizedEmail = "KADEN15@YAHOO.COM",
                            NormalizedUserName = "MARIANE22@HOTMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPxUtyw3bU7LlgSa++R2BFuh18HbpAeSSWubFoWaW0NJ/oinyN8ITujdilY4dq6U6Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "675c73d5-9d69-481f-bc6a-f33922659143",
                            SubscriptionType = "3",
                            TwoFactorEnabled = false,
                            Type = 0,
                            UserName = "Haylee.Pouros@gmail.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "871fda28-b47c-46b9-ae5f-92e1f9833a58",
                            Email = "Flavie_Cummings70@yahoo.com",
                            EmailConfirmed = true,
                            HasPaid = false,
                            HasSubscription = false,
                            IsBlocked = false,
                            LockoutEnabled = true,
                            MaxItemsPerYear = 0,
                            Name = "Juliana Mayer",
                            NormalizedEmail = "ALENE.COLE@HOTMAIL.COM",
                            NormalizedUserName = "GIOVANNI.ROGAHN@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBfUdzZ5f1PL5hAXdIFb/zoGE406nsXODDR2N0ZYzbP4YpmBV7oSJWKbu7rt60/lhQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06d7d4a6-eeb2-4588-ad7b-350275b6ecc6",
                            SubscriptionType = "4",
                            TwoFactorEnabled = false,
                            Type = 0,
                            UserName = "Gustave79@yahoo.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BiebWebApp.Models.Loan", b =>
                {
                    b.HasOne("BiebWebApp.Models.Item", "Item")
                        .WithMany("Loans")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiebWebApp.Models.Reservation", "Reservation")
                        .WithMany("Loans")
                        .HasForeignKey("ReservationId");

                    b.HasOne("BiebWebApp.Models.User", "User")
                        .WithMany("Loans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Reservation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BiebWebApp.Models.Reservation", b =>
                {
                    b.HasOne("BiebWebApp.Models.Item", "Item")
                        .WithMany("Reservations")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiebWebApp.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BiebWebApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BiebWebApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BiebWebApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BiebWebApp.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BiebWebApp.Models.Item", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("BiebWebApp.Models.Reservation", b =>
                {
                    b.Navigation("Loans");
                });

            modelBuilder.Entity("BiebWebApp.Models.User", b =>
                {
                    b.Navigation("Loans");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
